env:
  dev: true
event:
  execute:
    thread:
      max:
        size: 64
      min:
        size: 10
  update:
    result:
      thread:
        size: 32
logging:
  config: classpath:logback-boot.xml
spring:
  http:
    encoding:
      force: true
  redis:
    database: 0
    host: r-uf64798d0e840294.redis.rds.aliyuncs.com
    password: 5d7p9Rx89$s3^s%x
    pool:
      max-active: 200
      max-idle: 50
      max-wait: 3000
      min-idle: 10
    port: 6379
    timeout: 1000
  session:
    store-type: none
swagger:
  enable: true